apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: {{ dig "service" "type" "ClusterIP" .Values }}
  selector:
    app: myapp
  ports:
    - name: http
      port: {{ dig "service" "port" 8080 .Values }}
      targetPort: {{ dig "service" "targetPort" 8080 .Values }}
      protocol: TCP
