{{- /* 디버그: service의 실제 타입/값 보기 */ -}}
{{- /* 완료 후 반드시 삭제! */ -}}
{{- fail (printf "DEBUG .Values.service => type=%T value=%v" .Values.service .Values.service) -}}

apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: {{ dig .Values "service" "type" "ClusterIP" }}
  selector:
    app: myapp
  ports:
    - name: http
      port: {{ dig .Values "service" "port" 8080 }}
      targetPort: {{ dig .Values "service" "targetPort" 8080 }}
      protocol: TCP
