{{- $raw := .Values.service | default (dict) -}}
{{- $svc := ternary $raw (dict "type" $raw) (kindIs "map" $raw) -}}
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: {{ default "ClusterIP" $svc.type }}
  selector:
    app: myapp
  ports:
    - name: http
      port: {{ default 8080 $svc.port }}
      targetPort: {{ default 8080 $svc.targetPort }}
      protocol: TCP
