# Default values for myapp
replicaCount: 1
image:
  repository: harbor.local:30443/project/myapp
  tag: "52-839c162"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: harbor-cred

pod:
  hostAliases:
    - ip: "172.18.0.4"
      hostnames:
        - "harbor.local"


nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
config:
  port: 80
